### ISSUE TITLE
setupServer.sh misconfigured

### ISSUE THREAD

**Issue by EmpressFiona** [kavezo/MagiReco_NA_Server#40]
Having set up a NUC with Linux for unrelated reasons, I thought I'd set this up for fun as well. Unfortunately, it didn't go very well at first, and while it's *still* not going very well, I can at least provide some information on what went wrong for later.

>     default: *** BEGINNING ZIPZAP VM SETUP ***
>     default:
>     default: # Installing packages...
>     default:
>     default: WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
>     default: 5 packages can be upgraded. Run 'apt list --upgradable' to see them.
>     default:
>     default: # Disabling Ubuntu DNS manager...
>     default: Removed /etc/systemd/system/multi-user.target.wants/systemd-resolved.service.
>     default: Removed /etc/systemd/system/dbus-org.freedesktop.resolve1.service.
>     default:
>     default: # Setting up nginx web server in proxy mode...
>     default: # Generating SSL certificate...
>     default: python3: can't open file '../generate_cert.py': [Errno 2] No such file or directory
>     default: # Installing SSL certificate and starting up nginx...
>     default: cp: cannot stat '/ZipZap/ssl/ca.crt': No such file or directory
>     default: cp: cannot stat '/ZipZap/ssl/site.crt': No such file or directory
>     default: cp: cannot stat '/ZipZap/ssl/site.key': No such file or directory
>     default: Job for nginx.service failed because the control process exited with error code.
>     default: See "systemctl status nginx.service" and "journalctl -xe" for details.
>     default:
>     default: # Installing ZipZap python dependencies...
>     default: # Enabling ZipZap autostart at boot...
>     default: Created symlink /etc/systemd/system/multi-user.target.wants/rc-local.service → /etc/systemd/system/rc-local.service.
>     default:
>     default: # Starting ZipZap...
>     default:
>     default: *** ALL DONE! ***
>     default: This VM's public IP is: 192.168.1.244
>     default: Set your device/emulator's DNS to that address.
>     default: IP address is 192.168.1.244
>     default: Updating DNS 

This was after a `git clone`, but the same thing happened with the 0.5.3 source code release. (As an aside, the APK is only clearly placed in the Windows release zip...) I thought it might be an issue with the path of generate_cert.py being '../' instead of './', but that didn't fix it.

Further investigation revealed the problem was twofold. First, the ZipZap folder was mounted at `/ZipZap`, while the working directory remained at `/home/vagrant` (aka `~`.). So I fixed that by changing the working directory. Second, the relative path to the python script to generate certs was still incorrect anyway, so I fixed that too.

I've already edited the file and will make a pull request to fix this, but I can't say for certain whether it actually totally works as intended now. For instance, I keep getting network errors of 1, 10, and 110 while trying to download the tutorial content (which is downloading _extremely slowly_ either way). Switching to native Windows makes it work more smoothly, although not by much. There's still the occasional error when downloading, and the speed is still glacial on 5 GHz wifi that regularly handles much higher speeds.

Either there's some way of downloading the assets faster I'm not aware of, or I might recommend trying to find some way of creating a persistent cache or getting the files on the phone ahead of time. (Admittedly, I don't really know where the files are being pulled from in the first place...) The cache files also consistently only go up to less than 5 MB for the largest, and this is consistent on both the Vagrant VM and the Windows machine. (I've actually yet to get into the game at all, it's taken so long!)

Thus, I can't actually tell if the Vagrant version is working past simply letting me connect, get the cert, and download the files as expected. 

If it matters - this is a fresh install! Anything I could do to make it easier for myself and a couple of friends to install this in a timely fashion would help a lot; either a persistent local cache, or a way of installing the files to your phone beforehand, would work wonders.

**Comment by EmpressFiona** [comment]
Upon further examination, the slow network issue appears to be more a matter of the game downloading *all the files at once*, or at least I *think* that's what it's doing...so, we'll call that one user error. Sorry about that! (It said it'd download them in the background, and I thought it'd just go right into the tutorial...)

It'd still be great to have a ready-made setup, be it something you need root for to transfer from phone to phone, or a persistent cache that you can download ahead of time and transfer from server installation to server installation - or, more importantly, download all at once and install quickly over the local network when convenient. (Extra useful for emulator players - alas, I decided to use a real phone...albeit, it's still sending about as fast as it's grabbing the files.) The network errors are still an issue, though.

Is it safe to transfer the nginx cache between installations, or will it be converted to a transferrable cache once the downloads are done? I'm a bit unclear on how this all works, and poking through the source code didn't help much. (Then again, I'm not even sure *multiple users* are even supported...while I know the multiplayer features aren't really functional yet, I'd like to simplify setup for my friends in potential anticipation.)

**Comment by kavezo** [comment]
Oh yeah...sorry about that, on fresh installs the game really has to download everything from scratch, and in fact, since we've done a few optimizations on the lists of assets (asset_[main|voice|config|some other stuff I forgot].json.gz), it often thinks it has to redownload everything just because the asset lists have changed a lot. There's a way to prevent this on rooted devices that already have all the assets by editing madomagi.db, a sqlite3 database that stores versions of different files, but I haven't yet had the bandwidth to look into it.

Speaking of which though, the files themselves can be downloaded from [here](https://drive.google.com/file/d/19zmdv28dNYafw78NzQHH4nPhAebP-9Pe/view). These need to be placed in the /data/data/com.aniplex.magireco.en/files/madomagi folder. A caveat though -- it will _still_ kick off the downloads just because there's a mismatch in madomagi.db. Okay, yeah, now I'm convinced to take the madomagi.db investigation off the backlog, will hold off on putting the link in the readme until there's an actual way to stop the downloads from going xd

I'll take a look at the pull request when I have more time! I didn't work on the Vagrant scripts, and in fact couldn't test on my Linux side because the network didn't like it up until very recently, but it should be testable now.

Oh, and there's actually no plans to support the tutorial, unfortunately. After a lot of discussion with people about competition with MagiReco JP, I think the best decision is to not try to onboard new players who really need the tutorial, but rather just have something old users can continue to enjoy in ways they can't on JP. ~~besides it's a lot of work and I don't want to do it~~

As for all the network issues, that's actually a weird bug with the native app that we haven't been able to figure out -- it does something every 1000 files after which it just...dies, for some reason. Likely something non-essential to downloading things, maybe a checksum or something -- but it's hard to debug. In any case, this is more of a backlog item for now...

I believe the nginx cache is safe to transfer; we haven't changed anything about the cache. But once all the downloads are on the phone, the phone either saves them permanently or caches them too, so there's no problem of having to redownload everything when you only move to a new server version without changing things on the phone.

And...yeah, sorry, the server only serves _one user's_ information right now, regardless of the device. This user data (stored in data/user) can be changed for other people, but no more than one user can play at a time. Again, this is a feature that I'm holding off implementing until all the features for singleplayer are implemented, and most of the egregious bugs are fixed. If you're curious though, the main change that'll end up allowing multiple people to play one the same server I'm planning is to look for references to the data/user folder, and modify them to different directories based off of the `user-id-fba9x88mae` header in the request.

**Comment by EmpressFiona** [comment]
Having had the chance to give the game a proper try, things are still kinda not-great?

The game actually *launches* just fine - I'm not actually bent up about not having a tutorial, if I can see the story content for it in the archive. But there are indications it's not actually working properly from a comparison to a video of the Prologue. I'm *assuming* that playing back story events in the Archive skips battle sequences, as expected, but it's completely missing the voices in the Prologue other than Kyubey's.

When I try to watch the opening movie, it stops in a fairly consistent place every time, and Iroha's transformation movie also doesn't work properly.

(Oh, and I thought a chapter was missing from Another Story, but no, as it turns out, that's where it starts...confusing!)

As mentioned, I'm playing on a phone, and the downloads were unreliable at best to begin with; it's entirely possible the movies, etcetera, have been corrupted. Or the phone is just kind of not working very well; it's an older flagship, so it shouldn't be a huge issue on that end. More likely it's repeated attempts to re-download files or game crashes or such that's the issue.

Is it possible to stuff the assets from your Google Drive link into the nginx_windows/assets/magica folder? That folder currently stands empty, but I assume it's there for a reason. (The scenario JSONs seem to be different from the ones produced by installing from this server; what should I do with those? I assume I shouldn't overwrite the DB.)

Anyway, I'll do some more testing soon. Hope this helps!

**Comment by EmpressFiona** [comment]
Upon further inspection, the 'fullvoice' package was never actually downloaded, even though I requested it when installing - or at least, I'm pretty sure I did. Maybe related to the tutorial being skipped?

I may take the time to test it in an emulator on my desktop to make sure that it's not an issue of my phone being weird or my wifi being worse than I thought. That being said, on a *hunch*, I checked the `op_movie.usm` file my phone downloaded versus the file in the folder you linked off Google Drive; sure enough, the two files have different MD5s. (I suspect the one my phone downloaded to be corrupted in some way.)

Sure enough, while the `asset_main.json` file is slightly different from the phone copy to the Google Drive copy - though I suspect that to just be a structure thing - the MD5 for `op_movie.usm` in the JSON on my phone *still shows* the same MD5 as the Google Drive one does.

Specifically, the MD5s are:

Google Drive `op_movie.usm`, and the one listed in both `asset_main.json` files: `4C17DA3A644D8BDBBB05D9E6D993A4AB`
My phone's `op_movie.usm` downloaded through ZipZap: `8BD84C730D64072D570B2EB31C783419`

I strongly suspected this is why the video stopping at ten seconds problem happens, and sure enough...the OP plays the whole way through when I replace the file with the correct one! And there's decent chance this and other files being different from the canonical ones is the reason for several-other file problems with redownloading files; if the files are, in fact, different from what the JSONs expect, but for whatever reason it can't actually *determine* this through MD5 checks once the files are on the phone...of course it'd keep trying to redownload them! (I haven't actually had this happen to me yet, mind you.)

As for the reason the files are wrong in the first place? Clearly, either ZipZap/the app is damaging the files in transit, or the files from wherever it pulls it from are somehow wrong.

So yeah, I think I've solved your problem after a fashion, and this at least provides a reason for a lot of the strange symptoms I've been suffering; if I copy over all the right files, it should hopefully solve most of the issues. (The issue of it not downloading fullvoice might be solved through simply trying to redownload voices, too.)

~~As an aside, this is just the fangirl side talking, but the only thing I'm hoping for regarding the tutorial is that Mitama-related lines aren't skipped. That being *said*, since the dialogue is all in JSONs, in theory anything good can be added back in later.~~

**Comment by kavezo** [comment]
I think I know what's up. We changed the asset lists a _lot_, including moving all the story voices into asset_main.json.gz. Unfortunately, I believe there was an asset_tutorial.json.gz (or something) that we just forgot to add in there. We might have done something quirky with the fullvoice files too, I forgot xd

As for putting things in the nginx_windows/assets/magica folder -- it'll work with most of the assets, but some of them, especially movies and voices, need to be downloaded in 1 MB chunks, before the app stitches them together into one file. This is actually likely the reason why the movies stop partway through; in our asset json wrangling we must have messed up the chunks. Do you know how big the corrupted movie was? Perhaps the downloading of chunks stopped early...

**Comment by EmpressFiona** [comment]
The corrupted movie was the exact same size as the original one. The idea that the chunks have been rearranged makes sense to me, though; it seems like Magia Record does a lot of strange things behind the scenes with videos. The only odd thing is the app not being able to verify the MD5s except under certain circumstances (so I assume).

Is there any reason you didn't use the original JSONs? Besides to add new assets, I'm assuming. It strikes me that it'd make things less likely to break.

As for the voices, the fullvoices that is, I'd need to double check my phone, but I'm fairly certain that there was a folder entirely missing from that copy as opposed to the archive, presumably including the voices we need. That being said, the story files for the prologue scenario directly reference 'fullvoice', so it's likely either 

I don't have the time to check it today, I'm afraid. I'll try and check in later on.

**Comment by kavezo** [comment]
Yeah...I think we ended up redoing the files because it was a lot less work -- turns out there are tiny asset lists that get downloaded every time you play a story for the first time, and it was more of a hassle to put those together than it was to just shove all of those downloads into the initial download :/

**Comment by kavezo** [comment]
wait hold up -- I mentioned previously that you couldn't put big files into /magica because they actually existed in chunks. Turns out they don't actually exist in chunks, and nginx does all the chunking, so you can put them in there. The bug might actually be with nginx's chunking method, though. Haven't tested.

edit: never mind, I got too clever once I actually re-read the source code again. The part that handles chunks only knows how to do that for the files on the cloud =w= the bug could easily still be there though...

By the way, do you have a Discord? I can send you an invite to our discord server, and then we can finally close this issue xd

**Comment by EmpressFiona** [comment]
Re: the story voices, I took a look into the JSONs for the opening scenario, and this is what a typical line looks like:

```
{"bg":"bg_adv_46400.jpg","bgChangeEffect":"fade","bgm":"bgm01_anime06","chara":[{"cheek":0,"face":"mtn_ex_060.exp.json","id":200300,"motion":400,"pos":2,"voiceFull":"fullvoice/section_000001/vo_full_000001-1-6"}],"nameRight":"Homura","textBg":"shout","textRight":"[flashEffect:flashWhiteSlow1][bgEffect:shakeSmall]Ahhh!!!"}
```

That is, it's directly referencing the 'fullvoice' folder...which is nonexistent on the version installed on my phone. Indeed, I don't think the relevant files actually exist in any form on my phone! It *could* be possible that I didn't select the option to download those voices, but it might also be a bug.
(also, I'm not sure if it's referencing the actual files, or if it's using `asset_fullvoice.json` to check, but I suppose it'd be as easy as just putting the files onto my phone and seeing if the voices play, so I'll do that later - my DNS setup is now a bit more complicated, so I need to make absolutely sure I can get it to work...)

Either way, it *seems* like all I'd need to do is make sure the fullvoice folder is on the phone, and then just make sure any files made up of chunks are overwritten - which I *assume* is just the movie files, since everything else seems intact.

Anyway, I'll go add you on Discord, since you've listed yours~
